frontend:
	bash components/frontend.sh

cart:
	bash components/cart.sh

mongodb:
	bash components/mongodb.sh

frontendv1:
	bash components/frontendv1.sh

catalogue:
	bash components/catalogue.sh

redis:
	bash components/redis.sh

user:
	bash components/users.sh

mysql:
	bash components/mysql.sh

ship:
	bash components/shipping.sh

rabit:
	bash components/rabbitmq.sh

#Give proper output if argument is wrong, no need to handle the error