[mongodb]
mongodb.chakra86.store

[redis]
redis.chakra86.store

[mysql]
mysql.chakra86.store

[catalogue]
catalogue.chakra86.store

[rabbitmq]
rabbitmq.chakra86.store

[user]
user.chakra86.store

[cart]
cart.chakra86.store

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321