---
- name: Configure redis
  hosts: redis
  gather_facts: no
  become: yes
  tasks:
  - name: disable default redis
    command: dnf module disable redis -y
  
  - name: Enable redis:7
    command: dnf module enable redis:7 -y

  - name: Install redis
    dnf:
       name: redis
       state: present

  - name: update redis IP
    replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  
  - name: Disable protection
    lineinfile:
      path: /etc/redis/redis.conf
      regexp: "protected-mode"
      line: "protected-mode no"

  - name: Start redis
    systemd_service:
      name: redis
      state: started
      enabled: yes
